# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Bio
#     url: /
#     weight: 10
#   - name: Papers
#     url: /#papers
#     weight: 11
#   - name: Talks
#     url: /#talks
#     weight: 12
#   - name: News
#     url: /#news
#     weight: 13
#   - name: Experience
#     url: experience/
#     weight: 20
#   - name: Projects
#     url: projects/
#     weight: 30
#   - name: Teaching
#     url: teaching/
#     weight: 40

main:
- name: "\U0001F5D2 Posts"
  url: post/
  identifier: post
  weight: 200

- name: "\U0001F916 AI"
  url: docs/ai/
  identifier: ai
  weight: 300
- name: Machine Learning
  url: docs/ai/machine-learning
  identifier: ml
  parent: ai
  weight: 301
- name: Deep Learning
  url: docs/ai/deep-learning
  identifier: dl
  parent: ai
  weight: 302
- name: Computer Vision
  url: docs/ai/computer-vision
  identifier: cv
  parent: ai
  weight: 303
- name: Computer Vision
  url: docs/ai/computer-vision
  identifier: cv
  parent: ai
  weight: 304
- name: Natural Language Processing
  url: docs/ai/natural-language-processing
  identifier: nlp
  parent: ai
  weight: 305
- name: PyTorch
  url: docs/ai/pytorch
  identifier: pytorch
  parent: ai
  weight: 306

- name: "\U0001F9D1\u200D\U0001F4BB Coding"
  url: docs/coding/
  identifier: coding
  weight: 400
- name: Python
  url: docs/coding/python
  identifier: python
  parent: coding
  weight: 401
- name: Docker
  url: docs/coding/docker
  identifier: docker
  parent: coding
  weight: 402
- name: Linux
  url: docs/coding/linux
  identifier: linux
  parent: coding
  weight: 403
- name: Git
  url: docs/coding/git
  identifier: git
  parent: coding
  weight: 404
- name: C++
  url: docs/coding/c++
  identifier: c++
  parent: coding
  weight: 405
  
- name: "\U0001F4BB CS"
  url: docs/cs/
  identifier: cs
  weight: 500
- name: Algorithm
  url: docs/cs/algorithm
  identifier: algo
  parent: cs
  weight: 501
- name: Software Engineering
  url: docs/cs/software-engineering
  identifier: software-engineering
  parent: cs
  weight: 502
- name: Project Management
  url: docs/cs/project-management
  identifier: project-management
  parent: cs
  weight: 503
- name: Practical Skills
  url: docs/cs/practical-skills
  identifier: practical-skills
  parent: cs
  weight: 504
  
# - name: "\U0001F4DD Notes"
#   url: docs/notes/
#   identifier: notes
#   weight: 600
# - name: GIE
#   url: docs/notes/gestaltungsgrundsaetze-fuer-interaktive-echtzeitsysteme
#   identifier: gestaltungsgrundsaetze-fuer-interaktive-echtzeitsysteme
#   parent: notes
#   weight: 601
# - name: Rechnerstruktur
#   url: docs/notes/rechner-struktur
#   identifier: rechner-struktur
#   parent: notes
#   weight: 602
# - name: Telematics
#   url: docs/notes/telematics
#   identifier: telematics
#   parent: notes
#   weight: 603
# - name: MMWAB
#   url: docs/notes/mmwab
#   identifier: mmwab
#   parent: notes
#   weight: 604
# - name: Thesis
#   url: docs/notes/thesis
#   identifier: thesis
#   parent: notes
#   weight: 605
# - name: Jobs
#   url: docs/notes/jobs
#   identifier: jobs
#   parent: notes
#   weight: 606
# - name: SI
#   url: docs/notes/stochastische_informationsverarbeitung
#   identifier: si
#   parent: notes
#   weight: 607

# - name: "\U0001F468\u200D\U0001F3EB Online Courses"
#   url: online_courses/
#   identifier: online-courses
#   weight: 700
# - name: AWS ML Engineer Program
#   url: online_courses/aws_ml_engineer_program
#   identifier: aws-ML-engineer
#   parent: online-courses
#   weight: 701

- name: "\U0001F9FE R\xE9sum\xE9"
  url: uploads/resume.pdf
  identifier: resume
  weight: 800
