# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: cyan

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true  # Display the navigation bar?
    blox: "navbar"  # Choose a built-in navigation blox or create your own
    align: "center"  # Align menu links: `left`, `center`, or `right`
    fixed_to_top: true  # Fix the navigation bar to the top of the page
    show_search: true  # Let the user search from the navigation bar?
    show_theme_chooser: true  # Let the user choose between light or dark mode
    highlight_active_link: true  # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    logo:
      text: "Haobin Tan"
      filename: "icon.jpg"  # Logo filename in `assets/media/` folder

    # Shop a call-to-action button in the top right?
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/"

# Site footer
footer:
  copyright:
    notice: '© {year} Haobin Tan. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2006-01-02'
  time_format: '15:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - python
      - markdown
      - bash
      - shell
      - latex
      - yaml
    theme: "dracula"
  math:
    enable: true
  privacy_pack:
    enable: false
  diagram:
    enable: true
